BeatLeader/beatleader-website

- src/components/Common/PlayerNameWithFlag.svelte
- src/components/Dashboard/Ranking.svelte
- src/components/Dashboard/Songs.svelte
- src/components/Nav.svelte
- src/components/Player/ScoreServiceSwitcher.svelte
- src/components/Player/utils/service-param-manager.js
- src/components/Ranking/Mini.svelte
- src/network/clients/beatleader/players/utils/process.js
- src/network/clients/beatleader/scores/api-recent.js
- src/network/clients/beatleader/scores/api-top.js
- src/network/clients/beatleader/scores/api.js
- src/network/queues/beatleader/api-queue.js
- src/pages/About.svelte
- src/pages/Leaderboard.svelte
- src/pages/Ranking.svelte
- src/pages/Search.svelte
- src/services/beatleader/scores.js
- src/services/beatsavior.js
- src/stores/http/http-player-with-scores-store.js
- src/stores/http/http-scores-store.js
- src/stores/http/providers/api-player-with-scores.js
- src/stores/http/providers/api-scores.js
- src/stores/http/providers/utils/scores-fetch.js
- src/utils/format.js
- yarn.lock
Adds sorting and filtering of scores on the player page. As it was before for cached scores
Requires API endpoint update, here: https://github.com/BeatLeader/beatleader-server/blob/7d4441a23f5d6ca6bf6b3a55f34555d509aa55cf/Controllers/PlayerController.cs#L116
1. Add new sortBy cases (rank & stars)
2. Add ordering support (order GET param: asc/desc)
3. Add filtering support: by song name (search GET param), difficulty (diff GET param: easy/normal/hard/expert/expertplus) and ranked status (type GET param: ranked/unranked)
I think it would be helpful to standardize the naming of the sortBy parameter. I propose to change recent to date, topPP to pp, and topAcc to acc. Thanks to this, the sortBy parameter will simply define the field, by which it should be sorted, and the order parameter will …
> Add live scores sorting and filtering (needs API update)

- src/components/Common/Pager.svelte
> fix: mobile pager overflow

- src/components/Ranking/AccSaberMini.svelte
> fix: acc saber mini ranking when one of the categories contains no data

- src/pages/RtDashboard.svelte
I set this to make it easier to develop and forgot to remove it before PR.
> fix: hide map search tool by default

- src/components/Common/Accuracy.svelte
- src/components/Leaderboard/PPCurve.svelte
- src/components/Player/PlayerPerformance.svelte
- src/components/Score/Pp.svelte
- src/utils/beatleader/pp.js
I've added some line breaks to make the hover a bit easier to read:
I've also added the same functionality to nominated scores with mistakes.
I also extracted some logic out of PPCurve.svelte that needed to be used in places where fcPp wasn't available but fcAccuracy was.
> Adding line breaks to PP/Acc hover overs + adding hover to Nominated scores with mistakes

- .gitignore
- src/components/Player/Profile.svelte
Added an onkeyup listener in the "Profile" component, which, when the escape key is pressed during profile editing, it is cancelled. This functions the same as clicking the "Cancel" button, but attributes an intuitive keybind to it.
> Esc key now cancels profile editing

- src/components/Player/Profile.svelte
If the screenshot cannot be copied to clipboard, the site attempts to save it as a file with the user's username as it's filename.
> Screenshots now save when copying to clipboard is impossible

- src/components/Player/utils/profile.js
"Anonymous" is misspelled as "anonimus" in the mouseover text of the replays watched stat on user profiles:
This PR corrects the user-facing text, but internally the stat is still called `anonimusReplayWatched` so that nothing should break.
> Fix spelling of "anonymous"

- src/components/Leaderboard/Score.svelte
(continued from #192)
This fixes the mini profile badges when hovering a player name on a map leaderboard page or player profile page.
The global CSS here was also affecting the badges in the mini profile component, since it is nested within the score component.
It does feel a bit hacky, maybe this CSS could be moved into the lower level components instead.
> Fix mini profile badge alignment

- src/components/Common/MapTriangle.svelte
- src/components/Leaderboard/LeaderboardHeader.svelte
- src/pages/Leaderboard.svelte
- dynamic scaling of the triangle when modifiers are enabled and values exceed the default maxima
- the triangle on the leaderboard now takes into account the modifiers enabled on the pp curve
> Triangle tweaks

- src/components/Leaderboard/LeaderboardHeader.svelte
- src/pages/Leaderboard.svelte
Currently double clicking the hash element results in the selection including a trailing space like this 
Double clicking with the change in this PR
> Updated css of the map hash elements to remove the trailing space when double clicking

- src/pages/Leaderboard.svelte
The country filter was lost when changing pages if the leaderboard was displayed in the score details.
> Country leaderboard pager in the score details

- src/components/Player/Charts/AccMapsChart.svelte
fixes that the nodes for the average etc have the label to add them to a playlist
> Non-song nodes shouldn't have "add to playlist label" on maps acc graph

- src/pages/OauthSignIn.svelte
This scope is required for OAuth server to issue a refresh token.
Also fixed scopes delimiter - it's a space in OAuth specification, not a comma
> Add support for offline_access OAuth scope

- src/components/Leaderboard/Score.svelte
- src/components/Settings/LeaderboardSettings.svelte
- src/stores/config.js
super simple, just adds an option to show the hmd in the leaderboard scores. off by default
shows defaults rn because the api is returning defaults for hmd (0), controller (0) and platform (null) for some reason but there is no reason that it would not work with proper data.
> added hmd in leaderboard setting

- src/components/Common/Rain.svelte
- src/components/Common/RandomRain.svelte
Sometimes the rain on pages stays when navigating to other pages before the page where the rain is used has fully loaded. This directly applies to the profile page rain effects but might happen elsewhere too. When swapping before loading the rain doesn't get taken away and ends up being the top element, and then it blocks clicks. so disabling pointer events for now.
Visually not really an issue and goes away on refresh but this is an easy fix.
> fix rain blocking clicks in case it somehow ends up in front of elements

- src/pages/DeveloperPortal.svelte
- src/pages/SignIn.svelte
Adding some extra hoops to jump through and warnings for beatsaver login, because almost all users do not need it, but its often used to login when people get confused when trying to get their patreon rewards.
I'm not sure if mapper login should at all be mentioned on the sign in page, but for now I left this there:
this goes to the developer portal where I've just added a drop down for mapper login with some extensive warnings and red text, hopefully it's enough to make them realize along with being redirected to this page that they are on the wrong track.
> Try to prevent regular users from logging in with beatsaver

- src/App.svelte
Every time I click on this source button in the footer, I always get blindsided by the fact that It takes me to the Website's source instead of the GitHub organization (for example, when trying to get to the BL Server repo). I somewhat expect the source link to take me to the source for everything
> Change "Source" link in footer to the GitHub Organization

- src/utils/color.js
This gets rid of the errors (and unnecessary web traffic) when a theme tries to load a font that exists locally on the user's machine (that may not even exist on Google's font service). It's also smart about when a font is specified as a generic family name like sans-serif or monospace.
If a user specifies a font that they don't have locally on their system and doesn't exist in Google's font service it'll still throw an error (which is what we want; I think).
> Improved importFonts() so that it doesn't try to load invalid Google font URLs

- src/components/Common/ToolTip.svelte
- src/components/Player/Bio/BlBadges.svelte
Add new tooltip design to replace the HTML title attribute. Currently added to profile badges only but could be added to other places in the future.
> Make tooltips prettier

- src/components/Leaderboard/AttemptsGraph.svelte
- src/components/Leaderboard/ExmachinaCurve.svelte
- src/components/Leaderboard/LeaderboardAsideBox.svelte
- src/components/Leaderboard/LeaderboardDevMenu.svelte
- src/components/Leaderboard/LeaderboardStats.svelte
- src/components/Leaderboard/PPCurve.svelte
- src/components/Leaderboard/PredictedAccGraph.svelte
- src/components/Player/Achievements.svelte
- src/components/Settings/LeaderboardSettings.svelte
- src/pages/Leaderboard.svelte
- src/pages/Player.svelte
- src/stores/config.js
- src/utils/format.js
Added a singular component for the aside boxes, so they are consistent. With animation (horizontal animation not possible).
Forced all boxes to be a consistent width.
Better aligned the map details.
Improved map details overall.
Added a dev menu in map details (with toggle in settings) as a replacement for the hash.
Improved attempts hover. (better alignment with non-hovered status, kept success rate visible)
Improved pp curve overall.
Made modifier buttons on pp curve nicer and more consistent with the rest of the site.
Also made the nqt and rt boxes work with the new component.
Also made the profile page box for achievements more consistent.
> Leaderboard side boxes improvements & profile page achievements box improved
