- src/network/clients/beatleader/player/api.js
> fix: average accuracy badge for non-cached players

- src/network/clients/beatleader/scores/utils/process.js
- src/services/beatleader/scores.js
- src/stores/http/http-scores-store.js
> feat: add support for a new player scores endpoint response format

- src/components/Player/ScoreFilters/GenericFilter.svelte
- src/components/Player/ScoreFilters/RangeFilter.svelte
- src/components/Player/ScoreServiceSwitcher.svelte
- src/network/queues/beatleader/api-queue.js
- src/stores/http/providers/utils/scores-fetch.js
> feat: add filtering scores by map stars

- src/services/beatleader/scores.js
> fix: fetching cached scores after changing player scores endpoint

- src/App.svelte
- src/network/queues/beatleader/api-queue.js
- src/pages/Leaderboard.svelte
- src/pages/Leaderboards.svelte
- src/stores/http/enhancers/scores/scoreStatistic.js
- src/stores/http/http-leaderboard-store.js
- src/utils/filters.js
``/leaderboard`` API endpoint should support ``countries`` parameter (comma separated as in SS), or maybe single country support is enough? e.g. /leaderboard/id/188ba91?page=1&countries=PL
> feat: add song country leaderboard (needs API update)

- src/components/Player/Charts/AccHistoryChart.svelte
- src/components/Player/ProfileCards/BeatLeaderSwipeCard.svelte
- src/components/Player/utils/profile.js
- src/stores/http/http-scores-store.js
- ranked acc badge color
- main chart width on mobile
- rounding values in tooltip in acc history chart
> small stats fixes

- netlify.toml
- public/themes/mirror.css
- public/themes/mirror.less
- src/App.svelte
- src/components/Others/Settings.svelte
- src/stores/config.js
> Added a theme system to the website

- public/themes/mirror.css
- public/themes/mirror.less
- public/themes/unbounded.css
- public/themes/unbounded.less
> fixed when viewing a leaderboard, your own account isn't highlighted

- src/components/Common/SteamStats.svelte
- src/pages/Dashboard.svelte
> fix: friends ranking in classic theme overflowed the box

- src/services/beatleader/scores.js
> fix: date histogram labels

- src/components/Player/PlayerPerformance.svelte
IMO misses are more important stat than score
Before:
After:
> feat: add misses count to "vs me" stats

- src/components/Player/ScoresPager.svelte
the histogram is no longer hidden and shown again
> feat: improved histogram behavior when changing pages

- src/pages/Clan.svelte
> fix: player pp on the clan page

- public/themes/mirror.css
- public/themes/mirror.less
- src/network/clients/beatleader/leaderboard/api-leaderboard.js
- src/network/clients/beatleader/leaderboard/utils/process.js
- src/network/clients/beatleader/scores/api-player-score.js
- src/network/queues/beatleader/api-queue.js
- src/pages/Leaderboard.svelte
https://user-images.githubusercontent.com/1758707/177830718-29518d5d-7f23-4abe-849b-822b7785e9d2.mp4
> feat: make the player's score always visible on the leaderboard

- public/themes/mirror.css
- public/themes/mirror.less
- src/components/BeatSavior/Stats/Chart.svelte
- src/components/Player/PlayerPerformance.svelte
- src/network/queues/beatleader/api-queue.js
- src/pages/Leaderboard.svelte
- src/stores/http/enhancers/scores/scoreStatistic.js
> add score details to the song leaderboard

- src/components/Player/PlayerPerformance.svelte
- src/components/Player/SongScore.svelte
- src/network/clients/beatleader/scores/utils/process.js
- src/utils/date.js
> add prev date & misses count

- src/components/Leaderboard/PPCurve.svelte
- src/pages/Leaderboard.svelte
> add modifiers simulation to pp curve and increase acc precision to 0.1%

- src/components/Leaderboard/PPCurve.svelte
- src/components/Leaderboard/utils/regions-plugin.js
> add annotations to pp curve

- src/components/Player/ScoreFilters/TextFilter.svelte
https://discord.com/channels/921820046345523311/921826851528245318/1000700226463612979
> fix filtering by song name on mobile

- public/assets/dist/fix-ctrl-click.dev.js
- public/assets/fix-ctrl-click.js
- public/index.html
nsgolova plz decide whether merge it or close it
> fixed Ctrl+Click with some hacky ways

- src/pages/Leaderboard.svelte
https://discord.com/channels/921820046345523311/970233962213568522/1004761410552733706
> fix: score details on maps page

- src/components/Common/DateRange.svelte
- src/network/queues/beatleader/api-queue.js
- src/pages/Leaderboards.svelte
Note: It seems that filtering by date does not work in the API:
> add filtering maps by date range

- REMOVED.md
- TODO.md
- src/components/Rt/Summary.svelte
- src/pages/RtDashboard.svelte
- src/stores/localstorage.js
Event log, additional filtering and other tweaks
> RT dashboard

- src/components/Player/PinnedScore.svelte
- src/components/Player/PinnedScores.svelte
- src/components/Player/Profile.svelte
- src/pages/Player.svelte
- src/stores/beatleader/star-generator.js
also small fix for star generator errors
> opening pinned score details doesn't change a browser title now

- public/themes/dist/mirror.css
- public/themes/mirror.css
- public/themes/mirror.less
- src/components/Ranking/RankingTable.svelte
no more dashes in the ranking (I hope)
> fix: ranking stats

- src/components/Common/Button.svelte
- src/components/Event/Event.svelte
- src/pages/Events.svelte
also clicking on event leader now shows scores filtered to that event
> fix: event playlist buton

- src/pages/RtDashboard.svelte
And unrankeds are downloaded after qualified and nominated downloads are completed.
> fix: RT dashboard now downloads 50 maps per request. 

- src/components/Leaderboard/QualificationChange.svelte
- src/components/Leaderboard/QualificationStatus.svelte
- src/components/Leaderboard/ReweightChange.svelte
- src/components/Leaderboard/ReweightStatus.svelte
- src/components/Leaderboard/ReweightStatusRanked.svelte
- src/pages/Leaderboard.svelte
> feat: rank status change and basic changelog styling

- src/components/Common/Badge.svelte
- src/components/Player/Profile.svelte
Fixed issue where screenshots in most themes wouldn't work properly, where the text would be obscured. Applying position: relative to the badge css fixes the issue
> Fixed screenshotting issue

- src/components/Player/PlayerPerformance.svelte
https://discord.com/channels/921820046345523311/1076083820358545428
> fix: number of mistakes of previous score in score improvements did not include hit bombs

- src/App.svelte
- src/components/Nav.svelte
> add a simple replacement for hovers on mobile

- public/assets/ss-bulma.css
- src/components/Nav/Nav.svelte
- src/components/Player/ClanBadges.svelte
- src/pages/Leaderboard.svelte
> Fix leaderboard on tablet/mobile

- src/components/Score/AccuracySpreadChart.svelte
- src/components/Score/ExtendedAccGraphs.svelte
- src/utils/beatleader/process-replay-data.js
> split underswing chart into separate hands

- src/components/BeatSavior/Details.svelte
- src/components/Common/Accuracy.svelte
- src/components/Common/PerformanceBadge/Accuracy.svelte
- src/components/Common/PerformanceBadge/Label.svelte
- src/components/Common/PerformanceBadge/Mistakes.svelte
- src/components/Common/PerformanceBadge/Pp.svelte
- src/components/Common/PerformanceBadge/ScoreBadges.svelte
- src/components/Common/Value.svelte
- src/components/Player/FailedScore.svelte
- src/components/Player/PlayerPerformance.svelte
- src/components/Player/ScoreRank.svelte
- src/components/Player/SongScore.svelte
- src/components/Player/SongScoreDetails.svelte
- src/components/Score/CompactPagination.svelte
- src/components/Score/ReplayDetails.svelte
- src/components/Settings/DemoScores.svelte
- src/components/Settings/ScoreSettings.svelte
- src/components/Settings/Select.svelte
- src/network/queues/beatleader/api-queue.js
- src/pages/Leaderboard.svelte
- src/pages/Settings.svelte
- src/stores/config.js
- src/utils/beatleader/performance-badge.js
> Score editor

- src/components/Leaderboards/MapCardContent.svelte
https://discord.com/channels/921820046345523311/1093831986570874900/1093831986570874900
> fix: map url

- src/components/Ranking/RankingTable.svelte
Requires the server PR: https://github.com/BeatLeader/beatleader-server/pull/18
> Add the ability to sort by specific pp type on top PP leaderbaord

- src/components/BeatSavior/Details.svelte
- src/components/Player/SongScoreDetails.svelte
- src/components/Score/ExtendedAccGraphs.svelte
- src/components/Score/ReplayDetails.svelte
- src/utils/beatleader/open-replay-decoder.js
- src/utils/beatleader/pp.js
- src/utils/beatleader/process-replay-data.js
> add "lost by underswings" metrics

- src/components/Nav/Nav.svelte
https://discord.com/channels/921820046345523311/1101679994251530241/1101679994251530241
> feat: increase the height of menu items on touch devices

- src/pages/Event.svelte
https://discord.com/channels/921820046345523311/1102546595322531850
> fix: confetti prevents from clicking anything

- src/components/Leaderboard/MapTriangleSmall.svelte
- src/components/Player/SongCover.svelte
- src/components/Player/SongInfo.svelte
- src/components/Song/Difficulty.svelte
- src/utils/beatleader/pp.js
> Showing actual star rating and triangle on  player profile (with mods applied)

- src/components/Player/Charts/SkillTriangleChart.svelte
> feat: auto-scale skill triangle

- src/components/Common/Achievements/AchievementCompact.svelte
- src/components/Common/Switcher.svelte
- src/components/Leaderboard/ModifiersPicker/ModifiersFilter.svelte
- src/components/Player/Profile.svelte
- src/components/Player/ScoreFilters/GenericFilter.svelte
- src/components/Player/ScoreServiceFilters.svelte
- src/components/Player/ScoreServiceSwitcher.svelte
- src/network/clients/beatleader/player/process.js
- src/pages/Player.svelte
- src/stores/beatleader/profile-edit-model.js
> Add scores sorting and filtering customization

- package.json
- src/pages/About.svelte
- src/pages/Census.svelte
- src/pages/Clan.svelte
- src/pages/Clans.svelte
- src/pages/Dashboard.svelte
- src/pages/Event.svelte
- src/pages/Events.svelte
- src/pages/Followed.svelte
- src/pages/LandingPage.svelte
- src/pages/Leaderboard.svelte
- src/pages/Leaderboards.svelte
- src/pages/NotFound.svelte
- src/pages/OauthSignIn.svelte
- src/pages/Patreon.svelte
- src/pages/Player.svelte
- src/pages/Playlist.svelte
- src/pages/Playlists.svelte
- src/pages/Privacy.svelte
- src/pages/Ranking.svelte
- src/pages/Settings.svelte
- src/pages/SignIn.svelte
- src/pages/Socket.svelte
- src/pages/StaffDashboard.svelte
- src/pages/Support.svelte
- src/pages/SurveyAchievement.svelte
- src/pages/Twitch.svelte
- yarn.lock
see: https://github.com/BeatLeader/svelte-routing/commit/38380e129251ef1ecee9009f7687ad6e925873fb
> Use the newly added preserveScroll parameter in svelte-routing

- src/components/Common/PerformanceBadge/ScoreBadges.svelte
Fixed core reason, so it should work for any use case
> Rotating score badges

- src/components/Common/PerformanceBadge/ScoreBadges.svelte
- src/utils/beatleader/performance-badge.js
https://discord.com/channels/921820046345523311/1149140614517108808
> fix: duplicated score stats

- src/components/Common/FormattedDate.svelte
- src/components/Leaderboards/SongScoreCompact.svelte
- src/components/Player/FailedScore.svelte
- src/components/Player/SongScore.svelte
- src/components/Settings/ScoreSettings.svelte
- src/utils/date.js
Adds a bunch of defined dateformatting options for those that don't want to go with the default of the selected locale
> More Dateformatting Options

- src/pages/About.svelte
Removed SRT
Change wording from "Retired RT to Retired Staff"
Moved lackwiz to RT
Updated LackWiz's bio
> Updated about page

- src/pages/Clan.svelte
- src/pages/Player.svelte
Add arcviewer of 159c7 to FELA clan page, add youtube embed of map song to FELA member profile pages
> FELA clan effect

- src/components/Leaderboard/LeaderboardHeader.svelte
needed to clarify how old a diff precisely is
> show full date on hover for when dates all show as "last year"

- src/components/Nav/Nav.svelte
> Add unread badge for clan invites

- src/components/Player/utils/profile.js
- src/network/clients/beatleader/player/process.js
https://discord.com/channels/921820046345523311/1193988293713477803
> feat: add top global and country percentile badges to the player profile

- src/stores/http/http-scores-store.js
> fix: immer error introduced in ec36211c

- src/themes/flylight.less
commit with those removed dynamic selector thingies
> removed dynamic selector thingies for flylight theme
